movie_swiper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('movies.urls')),
]

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('leaderboard', views.TopMoviesView.as_view(), name='top_movies')
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver


class Movie(models.Model):
    title = models.CharField(max_length=256)
    year = models.CharField(max_length=256)
    runtime = models.CharField(max_length=256)
    rated = models.CharField(max_length=256)
    genre = models.CharField(max_length=256)
    director = models.CharField(max_length=256)
    actors = models.CharField(max_length=256)
    plot = models.TextField(max_length=256)
    language = models.CharField(max_length=256)
    awards = models.CharField(max_length=256)
    poster = models.CharField(max_length=256)
    rotten_tomato = models.CharField(max_length=256)
    imdb = models.CharField(max_length=256)
    metacritic = models.CharField(max_length=256)

    likes = models.IntegerField(default=0)
    vetos = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    movies_seen = models.ManyToManyField(Movie)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

movies/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import Movie
from . import imdb_scaper

import random

class TopMoviesView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'movies/top_movies.html'
    context_object_name = "context"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        movies = [movie for movie in Movie.objects.all() if movie.likes > 0]
        movies.sort(key=lambda x: x.likes, reverse=True)

        context.update({'movies': movies})
        return context


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'movies/index.html'
    context_object_name = "context"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # THIS IS ONLY FOR INITIALLY SCRAPING MOVIE DATA
        # AND IT HAS BEEN KEPT IN CASE OF EMERGENCY, DO NOT UNCOMMENT!

        # ids = imdb_scaper.get_ids()
        # for id in ids:
        #     movie_data = imdb_scaper.get_movie_data_from_id(id)
        #     movie = Movie(**movie_data)
        #     movie.save()

        random_movie = random.choice(Movie.objects.all())

        context.update({'movie': random_movie})
        return context

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        user = request.user
        movie = Movie.objects.get(pk=data["movie"])

        if "like" in data:
            print(f"Add a like to {movie}")
            user.profile.movies_seen.add(movie)
            movie.likes += 1
            movie.save()
        elif "veto" in data:
            print(f"Add a veto to {movie}")
            user.profile.movies_seen.add(movie)
            movie.vetos += 1
            movie.save()

        return self.get(self, request, *args, **kwargs)

movies/templates/movies/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie Swiper</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'movies:index' %}">
          <h1 class="title">Movie Picker</h1>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="{% url 'movies:index' %}">Vote</a>
          <a class="navbar-item" href="{% url 'movies:top_movies' %}">Leaderboard</a>
        </div>
      </div>
    </nav>

  <section class="section">
    <div class="container has-text-centered">
      <figure class="image is-inline-block">
        <img class="image" src="{{movie.poster}}"></img>
      </figure>

      </br>
      </br>

      <form method="POST" action=''>
        {% csrf_token %}
        <input type="hidden" name="movie" value="{{movie.id}}" />
        <div class="has-text-centered">
          <button class="button is-danger" name="veto">Veto</button>
          <button class="button" name="skip" onClick="window.location.reload();">Skip</button>
          {% if movie in user.profile.movies_seen.all %}
            <button class="button is-primary" name="like" disabled>Like</button>
          {% else %}
            <button class="button is-primary" name="like">Like</button>
          {% endif %}
        </div>
      </form>
      </br>

      <div class="box">
        <h1 class="title">{{movie.title}}</h1>
        <p>Year: {{movie.year}}</p>
        <p>Runtime: {{movie.runtime}}</p>
        <p>Rated: {{movie.rated}}</p>
        <p>Genre: {{movie.genre}}</p>
        <p>Director: {{movie.director}}</p>
        <p>Actors: {{movie.actors}}</p>
        <p>Language: {{movie.language}}</p>
        <p>Awards: {{movie.awards}}</p>
        <p>Rated: {{movie.rated}}</p>
      </div>

      <div class="box">
        <p>{{movie.plot}}</p>
      </div>

    </div>
  </section>

  <script>history.scrollRestoration = "manual"</script>
  <script>
  document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }
  });
  </script>

  </body>
</html>

movies/templates/movies/top_movies.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie Swiper</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'movies:index' %}">
          <h1 class="title">Movie Picker</h1>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="{% url 'movies:index' %}">Vote</a>
          <a class="navbar-item" href="{% url 'movies:top_movies' %}">Leaderboard</a>
        </div>
      </div>
    </nav>

  <section class="section">
    <div class="container has-text-centered">
      <h1 class="title">Top Movies</h1>
      <h3 class="subtitle">By Likes</h3>

      {% for movie in movies %}
        <p>{{movie}} - {{movie.likes}}</p>
      {% endfor %}

    </div>
  </section>

  <script>history.scrollRestoration = "manual"</script>
  <script>
  document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }
  });
  </script>
  </body>
</html>